version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  api1: &api
    image: ghcr.io/seuusuario/rinha-backend-2025-dotnet:latest
    hostname: api1
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
    networks:
      - backend
      - payment-processor
    volumes:
      - rinha-data:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "167MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2

volumes:
  rinha-data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
